name: reviewdog
on:
  push:
    branches: [ main-nuxt ]
  pull_request:
    branches: [ main-nuxt ]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.14.0
        with:
          level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          eslint_flags: "--quiet --ignore-path .gitignore --ext .js,.ts,.vue ."
          fail_on_error: true
          filter_mode: nofilter
